In [1]:
import torch

x = torch.tensor([1,2,3,4,5])

print(x)

tensor([1, 2, 3, 4, 5])


In [2]:
y = torch.tensor([[1,2],[3,4]])
print(y)

tensor([[1, 2],
        [3, 4]])


In [3]:
z = torch.zeros(4,4)
print(z)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [4]:
w = torch.ones(2,2)
print(w)

tensor([[1., 1.],
        [1., 1.]])


In [5]:
v = torch.rand(3,4)
print(v)

tensor([[0.1472, 0.9403, 0.7247, 0.8444],
        [0.3463, 0.7722, 0.5767, 0.8554],
        [0.4627, 0.6468, 0.7214, 0.4239]])


In [6]:
i = torch.tensor([10,30,50,70,90])

# print(i[0])
# print(i[2])

j = torch.tensor([[10,50,90],
                  [20,60,100]])
# print(j[0,[1]])
print(j[0,1])

print(j[1,2])

tensor(50)
tensor(100)


In [12]:
import torch 
x = torch.tensor([1., 2., 3., 4.])


y = torch.tensor([2., 4., 6., 8.])

w = torch.tensor(0.0)
b = torch.tensor(0.0)


y_pred = w * x + b

loss = ((y_pred - y) ** 2).mean()

print('Pridiction Values', y_pred)

print('Actual Value', y)

print("Loss", loss)

Pridiction Values tensor([0., 0., 0., 0.])
Actual Value tensor([2., 4., 6., 8.])
Loss tensor(30.)
